### ISSUE TITLE
switch to each-file module?

### ISSUE THREAD

**Issue by pdehaan** [chilts/seagull#5]
Saw [**each-file**](https://www.npmjs.com/package/each-file) on npm and it looked pretty neat... and greatly simplifies getting a directory of specific file types:

``` js
var path = require('path')

var eachFile = require('each-file')
var fm = require('front-matter')

eachFile('test/simple/content/*.md', function (file, cb) {
  var contents = fm(file.contents.toString())
  var attributes = contents.attributes
  var content = contents.body.trim()
  var name = path.basename(file.relative, '.md')

  console.log('path: %s', file.path)
  console.log('base: %s', file.base)
  console.log('relative: %s', file.relative)

  console.log('name: %s', name)

  console.log('attributes: %s', JSON.stringify(attributes, null, 2))
  console.log('content: %s', content)
  console.log('---')

  cb()
}, function () {
  console.log('fin!')
})

/*
path: test/simple/content/welcome-to-the-new-world.md
base: test/simple/content/
relative: welcome-to-the-new-world.md
name: welcome-to-the-new-world
attributes: {
  "title": "Welcome to the New World",
  "published": "2015-06-05T03:12:22.745Z",
  "type": "post"
}
content: This is the 2nd post.

---
*/
```

**Comment by chilts** [comment]
Yeah, I'll have a look. I think `read-fir-files` gives me files in child directories too, so I may stick with that (am going to recurse down inside `content/` in a future feature). Also, in an older project of mine I had `*.textile` files too as well as `*.md` so we may still do something specific for each file, though I may not add that to this project - dunno yet.

**Comment by chilts** [comment]
I guess I should probably close these issues! I think this is now old and has been superseded with some of the newer features and code I've added recently. :) Thanks anyway @pdehaan. Hope you're still doing well and enjoying life as usual.
